"""add score columns to games

Revision ID: e09a30e3d9e5
Revises: 0f6e30a0d48c
Create Date: 2026-04-08 03:43:36.613363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09a30e3d9e5'
down_revision: Union[str, None] = '0f6e30a0d48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('score_home', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('score_away', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'score_away')
    op.drop_column('games', 'score_home')
    # ### end Alembic commands ###
